language: java
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f $HOME/.gradle/caches/minecraft/ForgeVersion.json
  - rm -f $HOME/.gradle/caches/minecraft/ForgeVersion.json.etag
  - rm -fr $HOME/.gradle/caches/minecraft/deobfedDeps
  - rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - '$HOME/.gradle/wrapper'
    - '$HOME/.gradle/caches'

before_install: chmod +x gradlew

install: ./gradlew setupCIWorkspace

script: ./gradlew build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${GITHUB_TOKEN}
  file: 'build/libs/Cookie-Tools-{$TRAVIS_TAG}.jar'
  on:
    tags: true
