language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.gradle/wrapper'
    - '$HOME/.gradle/caches'

before_install: chmod +x gradlew

install: ./gradlew setupCIWorkspace

script: ./gradlew build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${GITHUB_TOKEN}
  file: build/libs/*.jar
  on:
    tags: true
